# Generated by Django 3.2.5 on 2021-08-02 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('title', models.CharField(default='No song title', max_length=100)),
                ('query', models.CharField(default='No query', max_length=100)),
                ('album', models.CharField(default='No album', max_length=100)),
                ('songId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('preview', models.CharField(blank=True, default='None', max_length=400, null=True)),
                ('external', models.CharField(default='No external URL', max_length=100)),
                ('uri', models.CharField(default='No URI', max_length=100)),
                ('duration', models.CharField(default='No duration', max_length=10)),
                ('mainArtist', models.CharField(default='No artist', max_length=100)),
                ('artists', models.CharField(default='No artists', max_length=100)),
                ('popularity', models.FloatField(default=0, max_length=101)),
                ('image', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('theType', models.CharField(default='No type', max_length=10)),
                ('albumId', models.CharField(default='None', max_length=100)),
                ('artistId', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SongReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songId', models.CharField(blank=True, default='No song', max_length=100, null=True)),
                ('albumId', models.CharField(blank=True, default='No album', max_length=100, null=True)),
                ('comment', models.CharField(default='No comment', max_length=500)),
                ('songTitle', models.CharField(blank=True, default='No song title', max_length=500, null=True)),
                ('albumTitle', models.CharField(blank=True, default='No album title', max_length=500, null=True)),
                ('songArtists', models.CharField(blank=True, default='No artists', max_length=500, null=True)),
                ('rating', models.FloatField(default=1, max_length=10)),
                ('time', models.CharField(default='No date', max_length=50)),
                ('image', models.CharField(default='No image', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
